Repository 100-hours-a-week/5-yeosa-ongi-ai, pull requests merged in 2025-05, with the labels that each got.

#18 Refactor/#17
  app/service/people.py
Labels: Refactor

#21 Feat/#19
  .gitignore
  app/api/controllers/album_embedding_controller.py
  app/api/controllers/album_people_controller.py
  app/api/endpoints/album_embedding_router.py
  app/api/endpoints/album_people_router.py
  app/config/settings.py
  app/main.py
  app/utils/image_loader.py
  requirements.txt
Labels: Feature

#23 chore: Dockerfile에 모델 가중치 자동 다운로드 추가
  Dockerfile
Labels: Chore

#27 Feature/#24 aesthetic regressor weight 업로드 및 불러오기 로직 추가
  app/model/aesthetic_regressor.pth
  app/model/aesthetic_regressor.py
Labels: Feature

#29 chore: health check api 반환 message 수정
  app/api/endpoints/album_health_router.py
Labels: Chore

#32 feat : change issue default label
  .github/ISSUE_TEMPLATE/feature-request-template.md
Labels: Feature

#38 fix: album_duplicate_controller.py 누락코드 수정
  app/api/controllers/album_duplicate_controller.py
Labels: BugFix

#41 fix: 슬래시 제거로 POST 리다이렉트(307) 문제 해결
  app/api/endpoints/album_category_router.py
  app/api/endpoints/album_duplicate_router.py
  app/api/endpoints/album_embedding_router.py
  app/api/endpoints/album_health_router.py
  app/api/endpoints/album_people_router.py
  app/api/endpoints/album_quality_router.py
  app/api/endpoints/album_score_router.py
Labels: BugFix

#45 fix: image_features 중복 로딩 수정
  app/api/controllers/album_category_controller.py
  app/api/controllers/album_duplicate_controller.py
  app/api/controllers/album_quality_controller.py
Labels: BugFix

#50 Refactor/#49
  app/main.py
Labels: Refactor

#51 Feat/#47
  app/api/controllers/album_people_controller.py
  app/api/endpoints/album_health_router.py
  app/api/endpoints/album_people_router.py
  app/service/people.py
  app/utils/image_loader.py
  app/utils/logging_decorator.py
Labels: Refactor

#52 Refactor/#48
  app/api/controllers/album_category_controller.py
  app/api/controllers/album_duplicate_controller.py
  app/api/controllers/album_embedding_controller.py
  app/api/controllers/album_people_controller.py
  app/api/controllers/album_quality_controller.py
  app/api/controllers/album_score_controller.py
  app/api/endpoints/album_category_router.py
  app/api/endpoints/album_duplicate_router.py
  app/api/endpoints/album_quality_router.py
  app/api/endpoints/album_score_router.py
  app/main.py
Labels: Refactor

#54 Refactor/#53
  app/api/endpoints/album_category_router.py
  app/api/endpoints/album_duplicate_router.py
  app/api/endpoints/album_embedding_router.py
  app/api/endpoints/album_people_router.py
  app/api/endpoints/album_quality_router.py
  app/api/endpoints/album_score_router.py
  app/core/task_queue.py
  app/main.py
  app/service/highlight.py
Labels: Refactor

#56 Feat/#55
  app/api/controllers/album_category_controller.py
  app/api/controllers/album_duplicate_controller.py
  app/api/controllers/album_embedding_controller.py
  app/api/controllers/album_people_controller.py
  app/api/controllers/album_quality_controller.py
  app/api/controllers/album_score_controller.py
  app/core/logger.py
  app/service/category.py
  app/service/duplicate.py
  app/service/embedding.py
  app/service/highlight.py
  app/service/people.py
  app/service/quality.py
  app/utils/logging_decorator.py
Labels: Refactor

#58 Refactor/#57
  app/model/category_features.pt
  app/service/category.py
Labels: Refactor

#61 Feat/#60
  app/config/settings.py
  app/utils/image_loader.py
  requirements.txt
Labels: Feature

#63 fix: AWS SDK 누락된 것 수정
  requirements.txt
Labels: Chore

#68 Feat/#67
  app/api/controllers/album_embedding_controller.py
  app/config/settings.py
  app/main.py
  app/utils/image_loader.py
Labels: BugFix

#69 Refactor/#59
  app/api/controllers/album_category_controller.py
  app/api/controllers/album_duplicate_controller.py
  app/api/controllers/album_embedding_controller.py
  app/api/controllers/album_quality_controller.py
  app/api/controllers/album_score_controller.py
  app/config/settings.py
  app/core/task_queue.py
  app/main.py
  app/model/ViT-B/32/aesthetic_regressor.pth
  app/model/ViT-B/32/category_features.pt
  app/model/ViT-B/32/quality_features.pt
  app/model/ViT-L/14/aesthetic_regressor.pth
  app/model/ViT-L/14/category_features.pt
  app/model/ViT-L/14/quality_features.pt
  app/model/aesthetic_regressor.py
  app/model/clip_loader.py
  app/service/category.py
  app/service/duplicate.py
  app/service/embedding.py
  app/service/highlight.py
  app/service/quality.py
Labels: Refactor

#71 Fix/#70
  app/api/controllers/album_embedding_controller.py
  app/config/settings.py
Labels: BugFix

#76 fix: 카테고리 프롬프트 임베딩 파일 수정
  app/model/ViT-B/32/category_features.pt
  app/model/ViT-L/14/category_features.pt
Labels: BugFix

#80 Feat/#79
  app/api/controllers/album_category_controller.py
  app/api/controllers/album_duplicate_controller.py
  app/api/controllers/album_embedding_controller.py
  app/api/controllers/album_people_controller.py
  app/api/controllers/album_quality_controller.py
  app/api/controllers/album_score_controller.py
  app/api/endpoints/album_category_router.py
  app/api/endpoints/album_duplicate_router.py
  app/api/endpoints/album_embedding_router.py
  app/api/endpoints/album_people_router.py
  app/api/endpoints/album_quality_router.py
  app/api/endpoints/album_score_router.py
  app/main.py
  app/model/clip_loader.py
  app/model/clip_preprocess.py
  app/utils/image_loader.py
  requirements.txt
Labels: Refactor

#82 Refactor/#81
  app/api/endpoints/album_category_router.py
  app/api/endpoints/album_duplicate_router.py
  app/api/endpoints/album_embedding_router.py
  app/api/endpoints/album_quality_router.py
  app/api/endpoints/album_score_router.py
  app/main.py
  app/utils/image_loader.py
Labels: Refactor

#84 Refactor/#83
  app/api/__init__.py
  app/api/controllers/album_people_controller.py
  app/api/endpoints/album_people_router.py
  app/main.py
  app/model/arcface_loader.py
  app/model/yolo_detector_loader.py
  app/service/people.py
Labels: Refactor

#92 Feature/#89
  app/api/controllers/album_quality_controller.py
  app/service/quality.py
Labels: Feature

#94 Refactor/#93
  app/api/controllers/album_quality_controller.py
  app/service/quality.py
Labels: Refactor

#97 CPU 최적화 완료 버전 dev->main
  app/api/__init__.py
  app/api/controllers/album_category_controller.py
  app/api/controllers/album_duplicate_controller.py
  app/api/controllers/album_embedding_controller.py
  app/api/controllers/album_people_controller.py
  app/api/controllers/album_quality_controller.py
  app/api/controllers/album_score_controller.py
  app/api/endpoints/album_category_router.py
  app/api/endpoints/album_duplicate_router.py
  app/api/endpoints/album_embedding_router.py
  app/api/endpoints/album_people_router.py
  app/api/endpoints/album_quality_router.py
  app/api/endpoints/album_score_router.py
  app/main.py
  app/model/arcface_loader.py
  app/model/clip_loader.py
  app/model/clip_preprocess.py
  app/model/yolo_detector_loader.py
  app/service/duplicate.py
  app/service/people.py
  app/service/quality.py
  app/utils/image_loader.py
  requirements.txt
Labels: Chore

#98 Fix/#90
  app/core/cache.py
  app/model/clip_loader.py
  app/model/clip_preprocess.py
Labels: BugFix

#103 Feat/#102
  .dockerignore
  Dockerfile
  app/main.py
  app/model/clip_loader.py
  app/model/clip_preprocess.py
  requirements.txt
Labels: Docker
