Repository 100-hours-a-week/5-yeosa-ongi-ai, pull requests merged in 2025-04, with the labels that each got.

#2 feat : CLIP model test
  .dockerignore
  .gitignore
  Dockerfile
  app/main.py
  category_features.pt
  core/__init__.py
  core/cache.py
  model/__init__.py
  model/aesthetic_regressor.py
  model/clip_loader.py
  requirements.txt
  schemas/__init__.py
  schemas/album_schema.py
  service/__init__.py
  service/category.py
  service/duplicate.py
  service/embedding.py
  service/highlight.py
  service/quality.py
  utils/__init__.py
  utils/image_loader.py
Labels: Feature

#4 Feat/#3
  .dockerignore
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-request-template.md
  .github/ISSUE_TEMPLATE/task-template.md
  .github/pull_request_template.md
  .gitignore
  .vscode/settings.json
  Dockerfile
  app/main.py
  category_features.pt
  core/__init__.py
  core/cache.py
  model/__init__.py
  model/aesthetic_regressor.py
  model/clip_loader.py
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  schemas/__init__.py
  schemas/album_schema.py
  service/__init__.py
  service/category.py
  service/duplicate.py
  service/embedding.py
  service/highlight.py
  service/quality.py
  utils/__init__.py
  utils/image_loader.py
Labels: Suggestion

#6 refactor: API 구조 Router/Controller/Service 분리
  app/api/__init__.py
  app/api/controllers/album_category_controller.py
  app/api/controllers/album_duplicate_controller.py
  app/api/controllers/album_embedding_controller.py
  app/api/controllers/album_score_controller.py
  app/api/endpoints/album_category_router.py
  app/api/endpoints/album_duplicate_router.py
  app/api/endpoints/album_embedding_router.py
  app/api/endpoints/album_score_router.py
  app/core/__init__.py
  app/core/cache.py
  app/main.py
  app/model/__init__.py
  app/model/aesthetic_regressor.py
  app/model/clip_loader.py
  app/schemas/__init__.py
  app/schemas/album_schema.py
  app/service/__init__.py
  app/service/category.py
  app/service/duplicate.py
  app/service/embedding.py
  app/service/highlight.py
  app/service/quality.py
  app/utils/__init__.py
  app/utils/image_loader.py
  utils/image_loader.py
Labels: Refactor

#10 Chore/#8
  category_features.pt
Labels: Chore

#12 feat: 한글로 번역된 카테고리 분류 기능 추가
  app/api/controllers/album_category_controller.py
  app/service/category.py
Labels: Feature

#16 test: 헬스체크용 API 생성(/health/info)
  app/api/__init__.py
  app/api/endpoints/album_health_router.py
  app/main.py
Labels: Test
