Repository 100-hours-a-week/5-yeosa-ongi-ai, pull requests merged in 2025-06, with the labels that each got.

#110 refactor: threshold 0으로 변경
  app/service/category.py
Labels: Refactor

#114 fix: scipy 버전 수정
  requirements.txt
Labels: BugFix

#204 fix: 코드위치 변경
  app/main.py
Labels: Feature
